const countries = [
  'Albania',
  'Algeria',
  'Argentina',
  'Australia',
  'Austria',
  'Armenia',
  'Belgium',
  'Bhutan',
  'Brazil',
  'Bulgaria',
  'Belarus',
  'Cameroon',
  'Canada',
  'Chile',
  'China',
  'Colombia',
  'Costa Rica',
  'Denmark',
  'Dominican Republic',
  'Ecuador',
  'El Salvador',
  'Ethiopia',
  'Estonia',
  'Fiji',
  'Finland',
  'France',
  'State of Palestine',
  'Germany',
  'Ghana',
  'Greece',
  'Guatemala',
  'Honduras',
  'China, Hong Kong Special Administrative Region',
  'Hungary',
  'Iran (Islamic Republic of)',
  'Iraq',
  'Ireland',
  'Italy',
  'Japan',
  'Kazakhstan',
  'Republic of Korea',
  'Kyrgyzstan',
  "Lao People's Democratic Republic",
  'Latvia',
  'Liberia',
  'Lithuania',
  'Luxembourg',
  'Malaysia',
  'Malta',
  'Mauritius',
  'Mexico',
  'Mongolia',
  'Republic of Moldova',
  'Oman',
  'Netherlands',
  'New Zealand',
  'Norway',
  'Pakistan',
  'Panama',
  'Paraguay',
  'Peru',
  'Poland',
  'Portugal',
  'Qatar',
  'Réunion',
  'Romania',
  'Russian Federation',
  'Serbia',
  'Slovenia',
  'South Africa',
  'Spain',
  'Sweden',
  'Switzerland',
  'Thailand',
  'Tunisia',
  'Turkey',
  'North Macedonia',
  'Egypt',
  'United Kingdom of Great Britain and Northern Ireland',
  'United Republic of Tanzania',
  'United States of America',
  'Uruguay'
];

module.exports = countries;
